name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # 毎日午前0時に自動生成
  workflow_dispatch:     # 手動実行もできる

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Yu-Maekawa8
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate GitHub contribution snake"
          add: "dist/*.svg"
